# Auto-generated file — DO NOT EDIT
# Source: ../src/uart_comms.h

TEENSY_UART_BAUD_RATE = 9600
CONTROL_BOARD_UART_BAUD_RATE = 9600
UART_BUFFER_SIZE = 64
HEARTBEAT_TIMEOUT_MS = 300
UART_START_BYTE = 170
UART_END_BYTE = 85
UART_PROTOCOL_VERSION = 1
UART_MAX_PAYLOAD = 64

class MODE:
    UART_MSG_NONE = 0
    UART_MSG_HEARTBEAT = 1
    UART_MSG_SHUTDOWN = 2
    UART_MSG_STIM = 3
    UART_MSG_RECORD = 4
    UART_MSG_UPDATE_WIDTH = 5
    UART_MSG_UPDATE_AMP = 6
    UART_MSG_ACK = 7
    UART_MSG_ERROR = 8
    UART_MSG_GET_PARAMS = 9
    UART_MSG_START_STIM = 10
    UART_MSG_SEND_WIDTH = 11
    UART_MSG_SEND_AMP = 12
    UART_MSG_UNLOCK = 13
    UART_MSG_READY = 14

class PAYLOAD_TYPE:
    PAYLOAD_NONE = 0
    PAYLOAD_INT32 = 1
    PAYLOAD_FLOAT32 = 2
    PAYLOAD_BYTES = 3

class SHUTDOWN_SRC:
    SHUTDOWN_SRC_UNKNOWN = 0
    SHUTDOWN_SRC_CONTROL = 1
    SHUTDOWN_SRC_STIM = 2
    SHUTDOWN_SRC_PI = 3
