# Auto-generated file — DO NOT EDIT
# Source: ../src/uart_comms.h

TEENSY_UART_BAUD_RATE = 9600
CONTROL_BOARD_UART_BAUD_RATE = 9600
UART_BUFFER_SIZE = 64
HEARTBEAT_TIMEOUT_MS = 600
UART_START_BYTE = 170
UART_END_BYTE = 85
UART_PROTOCOL_VERSION = 1
UART_MAX_PAYLOAD = 64

class MODE:
    UART_MSG_NONE = 0
    UART_MSG_HEARTBEAT = 1
    UART_MSG_SHUTDOWN = 2
    UART_MSG_STIM = 3
    UART_MSG_RECORD = 4
    UART_MSG_UPDATE_WIDTH = 5
    UART_MSG_UPDATE_AMP = 6
    UART_MSG_ACK = 7
    UART_MSG_ERROR = 8
    UART_MSG_GET_PARAMS = 9
    UART_MSG_START_STIM = 10
    UART_MSG_SEND_WIDTH = 11
    UART_MSG_SEND_AMP = 12
    UART_MSG_UNLOCK = 13
    UART_MSG_READY = 14
    UART_MSG_STATUS = 15

class PAYLOAD_TYPE:
    PAYLOAD_NONE = 0
    PAYLOAD_INT32 = 1
    PAYLOAD_FLOAT32 = 2
    PAYLOAD_BYTES = 3

class SHUTDOWN_SRC:
    SHUTDOWN_SRC_UNKNOWN = 0
    SHUTDOWN_SRC_CONTROL = 1
    SHUTDOWN_SRC_STIM = 2
    SHUTDOWN_SRC_PI = 3
    SHUTDOWN_SRC_CONTROL_PI_HEARTBEAT_LOSS = 4
    SHUTDOWN_SRC_CONTROL_STIM_HEARTBEAT_LOSS = 5
    SHUTDOWN_SRC_STIM_CONTROL_HEARTBEAT_LOSS = 6

class STATUS_CODE:
    STATUS_INTERLOCK_ON = 1
    STATUS_INTERLOCK_OFF = 2
    STATUS_STIM_ON = 3
    STATUS_STIM_OFF = 4
    STATUS_DAC_VALUE_SET = 5
    STATUS_DAC_ZEROED = 6
    STATUS_CTRL_SHUTDOWN_RTN = 100
    STATUS_CTRL_STIM_RTN = 101
    STATUS_CTRL_AMP_RTN = 102
    STATUS_CTRL_STIM_LINK_UP = 103
    STATUS_SYSTEM_SAFE_LOCKED = 110
    STATUS_SYSTEM_IDLE_UNLOCKED = 111
    STATUS_SYSTEM_STIMULATING = 112
    STATUS_SYSTEM_RECORDING = 113

class SYSTEM_STATE:
    SYSTEM_SAFE_LOCKED = 0
    SYSTEM_IDLE_UNLOCKED = 1
    SYSTEM_STIMULATING = 2
    SYSTEM_RECORDING = 3
